require("systems/timers")

require("config/survival_config")
require("config/hero_config")
require("config/xp_config")
require("config/world_level_config")
require("config/zone_config")
require("config/drop_tables")
require("config/item_tier_config")
require("config/crafting_recipes")
require("config/artifact_config")
require("config/pet_config")
require("config/season_config")
require("config/boss_mechanics_config")

require("abilities/sirv_abilities")
require("items/sirv_items")

require("systems/sirv_utils")
require("systems/player_progression_system")
require("systems/player_life_system")
require("systems/safe_zone_system")
require("systems/world_level_system")
require("systems/zone_system")
require("systems/respawn_system")
require("systems/enemy_spawn_system")
require("systems/boss_system")
require("systems/drop_system")
require("systems/shop_system")
require("systems/crafting_system")
require("systems/artifact_system")
require("systems/pet_system")
require("systems/season_system")
require("systems/save_system")
require("systems/ui_event_system")
