DropTables = {
    ["common"] = {
        ["chance"] = 12,
        ["materials"] = 10,
        ["rarity_weights"] = {
            ["basic"] = 80,
            ["common"] = 20,
            ["rare"] = 0,
            ["epic"] = 0,
            ["legendary"] = 0,
            ["mythic"] = 0,
            ["divine"] = 0,
        },
    },
    ["elite"] = {
        ["chance"] = 45,
        ["materials"] = 40,
        ["rarity_weights"] = {
            ["basic"] = 35,
            ["common"] = 45,
            ["rare"] = 20,
            ["epic"] = 0,
            ["legendary"] = 0,
            ["mythic"] = 0,
            ["divine"] = 0,
        },
    },
    ["area_boss"] = {
        ["chance"] = 100,
        ["materials"] = 100,
        ["rarity_weights"] = {
            ["basic"] = 0,
            ["common"] = 45,
            ["rare"] = 40,
            ["epic"] = 15,
            ["legendary"] = 0,
            ["mythic"] = 0,
            ["divine"] = 0,
        },
        ["artifact_chance"] = 12,
    },
    ["zone_boss"] = {
        ["chance"] = 100,
        ["materials"] = 100,
        ["rarity_weights"] = {
            ["basic"] = 0,
            ["common"] = 0,
            ["rare"] = 55,
            ["epic"] = 35,
            ["legendary"] = 10,
            ["mythic"] = 0,
            ["divine"] = 0,
        },
        ["artifact_chance"] = 28,
        ["pet_fragment_chance"] = 10,
    },
    ["world_boss"] = {
        ["chance"] = 100,
        ["materials"] = 100,
        ["rarity_weights"] = {
            ["basic"] = 0,
            ["common"] = 0,
            ["rare"] = 0,
            ["epic"] = 20,
            ["legendary"] = 45,
            ["mythic"] = 25,
            ["divine"] = 10,
        },
        ["artifact_chance"] = 45,
        ["pet_fragment_chance"] = 20,
    },
    ["world_level_rarity"] = {
        [1] = {
            "basic",
            "common",
        },
        [2] = {
            "basic",
            "common",
            "rare",
        },
        [3] = {
            "basic",
            "common",
            "rare",
            "epic",
        },
        [4] = {
            "basic",
            "common",
            "rare",
            "epic",
            "legendary",
        },
        [5] = {
            "basic",
            "common",
            "rare",
            "epic",
            "legendary",
        },
        [6] = {
            "basic",
            "common",
            "rare",
            "epic",
            "legendary",
            "mythic",
        },
        [7] = {
            "basic",
            "common",
            "rare",
            "epic",
            "legendary",
            "mythic",
        },
        [8] = {
            "basic",
            "common",
            "rare",
            "epic",
            "legendary",
            "mythic",
            "divine",
        },
        [9] = {
            "basic",
            "common",
            "rare",
            "epic",
            "legendary",
            "mythic",
            "divine",
        },
        [10] = {
            "basic",
            "common",
            "rare",
            "epic",
            "legendary",
            "mythic",
            "divine",
        },
    },
}
