HeroConfig = {
    ["npc_dota_hero_axe"] = {
        ["id"] = "iron_guardian",
        ["display_es"] = "Guardián de Hierro",
        ["display_en"] = "Iron Guardian",
        ["role"] = "Tanque principal",
        ["attribute"] = "strength",
        ["abilities"] = {
            "sirv_iron_guardian_q",
            "sirv_iron_guardian_w",
            "sirv_iron_guardian_e",
            "sirv_iron_guardian_d",
            "sirv_iron_guardian_r",
        },
    },
    ["npc_dota_hero_centaur"] = {
        ["id"] = "oath_colossus",
        ["display_es"] = "Coloso Juramentado",
        ["display_en"] = "Oathbound Colossus",
        ["role"] = "Tanque y soporte defensivo",
        ["attribute"] = "strength",
        ["abilities"] = {
            "sirv_oath_colossus_q",
            "sirv_oath_colossus_w",
            "sirv_oath_colossus_e",
            "sirv_oath_colossus_d",
            "sirv_oath_colossus_r",
        },
    },
    ["npc_dota_hero_sven"] = {
        ["id"] = "crimson_berserker",
        ["display_es"] = "Berserker Carmesí",
        ["display_en"] = "Crimson Berserker",
        ["role"] = "DPS de fuerza",
        ["attribute"] = "strength",
        ["abilities"] = {
            "sirv_crimson_berserker_q",
            "sirv_crimson_berserker_w",
            "sirv_crimson_berserker_e",
            "sirv_crimson_berserker_d",
            "sirv_crimson_berserker_r",
        },
    },
    ["npc_dota_hero_bristleback"] = {
        ["id"] = "mountain_breaker",
        ["display_es"] = "Rompemontañas",
        ["display_en"] = "Mountain Breaker",
        ["role"] = "DPS AoE físico",
        ["attribute"] = "strength",
        ["abilities"] = {
            "sirv_mountain_breaker_q",
            "sirv_mountain_breaker_w",
            "sirv_mountain_breaker_e",
            "sirv_mountain_breaker_d",
            "sirv_mountain_breaker_r",
        },
    },
    ["npc_dota_hero_omniknight"] = {
        ["id"] = "ash_paladin",
        ["display_es"] = "Paladín de Ceniza",
        ["display_en"] = "Ash Paladin",
        ["role"] = "Healer híbrido",
        ["attribute"] = "strength",
        ["abilities"] = {
            "sirv_ash_paladin_q",
            "sirv_ash_paladin_w",
            "sirv_ash_paladin_e",
            "sirv_ash_paladin_d",
            "sirv_ash_paladin_r",
        },
    },
    ["npc_dota_hero_phantom_assassin"] = {
        ["id"] = "night_blade",
        ["display_es"] = "Hoja Nocturna",
        ["display_en"] = "Night Blade",
        ["role"] = "Asesino burst",
        ["attribute"] = "agility",
        ["abilities"] = {
            "sirv_night_blade_q",
            "sirv_night_blade_w",
            "sirv_night_blade_e",
            "sirv_night_blade_d",
            "sirv_night_blade_r",
        },
    },
    ["npc_dota_hero_riki"] = {
        ["id"] = "venom_dancer",
        ["display_es"] = "Bailarín Venenoso",
        ["display_en"] = "Venom Dancer",
        ["role"] = "Asesino DoT",
        ["attribute"] = "agility",
        ["abilities"] = {
            "sirv_venom_dancer_q",
            "sirv_venom_dancer_w",
            "sirv_venom_dancer_e",
            "sirv_venom_dancer_d",
            "sirv_venom_dancer_r",
        },
    },
    ["npc_dota_hero_juggernaut"] = {
        ["id"] = "agile_hunter",
        ["display_es"] = "Cazador Ágil",
        ["display_en"] = "Agile Hunter",
        ["role"] = "DPS velocidad",
        ["attribute"] = "agility",
        ["abilities"] = {
            "sirv_agile_hunter_q",
            "sirv_agile_hunter_w",
            "sirv_agile_hunter_e",
            "sirv_agile_hunter_d",
            "sirv_agile_hunter_r",
        },
    },
    ["npc_dota_hero_drow_ranger"] = {
        ["id"] = "dawn_archer",
        ["display_es"] = "Arquero del Alba",
        ["display_en"] = "Dawn Archer",
        ["role"] = "DPS rango crítico",
        ["attribute"] = "agility",
        ["abilities"] = {
            "sirv_dawn_archer_q",
            "sirv_dawn_archer_w",
            "sirv_dawn_archer_e",
            "sirv_dawn_archer_d",
            "sirv_dawn_archer_r",
        },
    },
    ["npc_dota_hero_windrunner"] = {
        ["id"] = "wind_monk",
        ["display_es"] = "Monje del Viento",
        ["display_en"] = "Wind Monk",
        ["role"] = "Soporte DPS y evasión",
        ["attribute"] = "agility",
        ["abilities"] = {
            "sirv_wind_monk_q",
            "sirv_wind_monk_w",
            "sirv_wind_monk_e",
            "sirv_wind_monk_d",
            "sirv_wind_monk_r",
        },
    },
    ["npc_dota_hero_crystal_maiden"] = {
        ["id"] = "frost_arcanist",
        ["display_es"] = "Arcanista de Escarcha",
        ["display_en"] = "Frost Arcanist",
        ["role"] = "Mago control AoE",
        ["attribute"] = "intellect",
        ["abilities"] = {
            "sirv_frost_arcanist_q",
            "sirv_frost_arcanist_w",
            "sirv_frost_arcanist_e",
            "sirv_frost_arcanist_d",
            "sirv_frost_arcanist_r",
        },
    },
    ["npc_dota_hero_lina"] = {
        ["id"] = "fire_sage",
        ["display_es"] = "Sabio Ígneo",
        ["display_en"] = "Fire Sage",
        ["role"] = "Mago DPS burst",
        ["attribute"] = "intellect",
        ["abilities"] = {
            "sirv_fire_sage_q",
            "sirv_fire_sage_w",
            "sirv_fire_sage_e",
            "sirv_fire_sage_d",
            "sirv_fire_sage_r",
        },
    },
    ["npc_dota_hero_oracle"] = {
        ["id"] = "vital_oracle",
        ["display_es"] = "Oráculo Vital",
        ["display_en"] = "Vital Oracle",
        ["role"] = "Healer principal",
        ["attribute"] = "intellect",
        ["abilities"] = {
            "sirv_vital_oracle_q",
            "sirv_vital_oracle_w",
            "sirv_vital_oracle_e",
            "sirv_vital_oracle_d",
            "sirv_vital_oracle_r",
        },
    },
    ["npc_dota_hero_dazzle"] = {
        ["id"] = "lunar_cleric",
        ["display_es"] = "Clérigo Lunar",
        ["display_en"] = "Lunar Cleric",
        ["role"] = "Healer y escudos",
        ["attribute"] = "intellect",
        ["abilities"] = {
            "sirv_lunar_cleric_q",
            "sirv_lunar_cleric_w",
            "sirv_lunar_cleric_e",
            "sirv_lunar_cleric_d",
            "sirv_lunar_cleric_r",
        },
    },
    ["npc_dota_hero_shadow_shaman"] = {
        ["id"] = "void_scholar",
        ["display_es"] = "Erudito del Vacío",
        ["display_en"] = "Void Scholar",
        ["role"] = "Debuffer y mago control",
        ["attribute"] = "intellect",
        ["abilities"] = {
            "sirv_void_scholar_q",
            "sirv_void_scholar_w",
            "sirv_void_scholar_e",
            "sirv_void_scholar_d",
            "sirv_void_scholar_r",
        },
    },
}
