ItemTierConfig = {
    rarities = {
        "basic",
        "common",
        "rare",
        "epic",
        "legendary",
        "mythic",
        "divine",
    },
    rarity_display_es = {
        ["basic"] = "Básico",
        ["common"] = "Común",
        ["rare"] = "Raro",
        ["epic"] = "Épico",
        ["legendary"] = "Legendario",
        ["mythic"] = "Mítico",
        ["divine"] = "Divino",
    },
    tiers = { 1, 2, 3, 4, 5 },
    lineages = { "standard", "ancient", "corrupt", "astral", "primordial" },
    slots = {
        "weapon",
        "head",
        "chest",
        "cape",
        "boots",
        "relic",
        "backpack",
    },
    roles = {
        "tank",
        "melee_dps",
        "ranged_dps",
        "assassin",
        "mage",
        "healer",
        "support",
    },
    stat_ranges = {
        [1] = {
            bonus_health = { 80, 180 },
            bonus_mana = { 40, 110 },
            bonus_damage = { 5, 18 },
            bonus_armor = { 1, 4 },
            bonus_resist = { 2, 7 },
            bonus_ms = { 8, 28 },
            bonus_primary = { 2, 6 },
            bonus_attack_speed = { 5, 18 },
            bonus_attack_range = { 35, 90 },
            heal_amp = { 3, 8 },
            aggro_reduction = { 3, 9 },
            evasion = { 2, 7 },
        },
        [2] = {
            bonus_health = { 180, 360 },
            bonus_mana = { 100, 220 },
            bonus_damage = { 14, 34 },
            bonus_armor = { 3, 8 },
            bonus_resist = { 5, 12 },
            bonus_ms = { 18, 42 },
            bonus_primary = { 5, 12 },
            bonus_attack_speed = { 14, 34 },
            bonus_attack_range = { 70, 140 },
            heal_amp = { 7, 14 },
            aggro_reduction = { 7, 15 },
            evasion = { 5, 12 },
        },
        [3] = {
            bonus_health = { 340, 620 },
            bonus_mana = { 200, 390 },
            bonus_damage = { 28, 58 },
            bonus_armor = { 6, 13 },
            bonus_resist = { 10, 20 },
            bonus_ms = { 30, 58 },
            bonus_primary = { 10, 22 },
            bonus_attack_speed = { 28, 58 },
            bonus_attack_range = { 110, 210 },
            heal_amp = { 12, 22 },
            aggro_reduction = { 12, 24 },
            evasion = { 9, 18 },
        },
        [4] = {
            bonus_health = { 580, 980 },
            bonus_mana = { 360, 650 },
            bonus_damage = { 52, 95 },
            bonus_armor = { 11, 20 },
            bonus_resist = { 18, 30 },
            bonus_ms = { 44, 76 },
            bonus_primary = { 18, 34 },
            bonus_attack_speed = { 48, 92 },
            bonus_attack_range = { 160, 290 },
            heal_amp = { 20, 34 },
            aggro_reduction = { 20, 36 },
            evasion = { 15, 27 },
        },
        [5] = {
            bonus_health = { 900, 1500 },
            bonus_mana = { 600, 980 },
            bonus_damage = { 88, 150 },
            bonus_armor = { 18, 32 },
            bonus_resist = { 28, 45 },
            bonus_ms = { 62, 100 },
            bonus_primary = { 30, 52 },
            bonus_attack_speed = { 82, 145 },
            bonus_attack_range = { 240, 420 },
            heal_amp = { 32, 52 },
            aggro_reduction = { 32, 55 },
            evasion = { 24, 40 },
        },
    },
    role_stat_focus = {
        tank = { "bonus_health", "bonus_armor", "bonus_resist", "aggro_reduction" },
        melee_dps = { "bonus_damage", "bonus_attack_speed", "bonus_health", "evasion" },
        ranged_dps = { "bonus_damage", "bonus_attack_speed", "bonus_attack_range", "evasion" },
        assassin = { "bonus_damage", "bonus_attack_speed", "bonus_ms", "evasion" },
        mage = { "bonus_damage", "bonus_primary", "bonus_mana", "bonus_attack_range" },
        healer = { "heal_amp", "bonus_mana", "bonus_resist", "aggro_reduction" },
        support = { "heal_amp", "bonus_resist", "bonus_health", "aggro_reduction" },
    },
    source_rules = {
        shop = "Stats fijos. No se usa como material de crafteo.",
        drop = "Stats variables por tier/rango cuando exista el sistema de instancias.",
        craft = "Stats variables por tier/rango cuando exista el sistema de instancias; puede alimentar recetas superiores.",
    },
    economy_rules = {
        shop_sell_ratio = 0.35,
        aggro_reduction_policy = "rara; principal en healer, support y ranged_dps defensivo",
        crafted_inventory_name_policy = "usar items base hasta implementar item_instance_id; luego mostrar nombre propio real",
        binding_policy = "soportar items ligados al heroe y items tradeables dentro de la cuenta",
    },
    fusion_rules = {
        can_fail_from_tier = 3,
        mitigation_items = true,
        failure_can_consume_gold = true,
        failure_can_consume_materials = true,
        failure_can_consume_one_input = true,
        negative_affixes_allowed = true,
        note = "La fusion real requiere sistema de instancias para no romper items genericos de KV.",
    },
}
