PetConfig = {
    ["stone_cub"] = {
        name_es = "Cachorro de Piedra",
        role = "tanque",
        unit = "npc_sirv_pet_stone_cub",
        active = "taunt_guard",
        unlock_level = 20,
        rarity = "common",
        stats = {
            health = { 90, 160 },
            armor = { 2, 5 },
        },
    },
    ["moon_wisp"] = {
        name_es = "Brizna Lunar",
        role = "healer",
        unit = "npc_sirv_pet_moon_wisp",
        active = "periodic_heal",
        unlock_level = 20,
        rarity = "rare",
        stats = {
            heal_amp = { 4, 9 },
            mana = { 60, 140 },
        },
    },
    ["ember_imp"] = {
        name_es = "Diablillo de Brasa",
        role = "dps_magico",
        unit = "npc_sirv_pet_ember_imp",
        active = "periodic_magic_damage",
        unlock_level = 20,
        rarity = "rare",
        stats = {
            magic_damage = { 4, 11 },
        },
    },
    ["iron_hawk"] = {
        name_es = "Halcon de Hierro",
        role = "dps_fisico",
        unit = "npc_sirv_pet_iron_hawk",
        active = "periodic_physical_damage",
        unlock_level = 20,
        rarity = "epic",
        stats = {
            damage = { 8, 20 },
            crit = { 3, 8 },
        },
    },
    ["shadow_wolf"] = {
        name_es = "Lobo Sombrio",
        role = "dps_fisico",
        unit = "npc_sirv_pet_shadow_wolf",
        active = "periodic_physical_damage",
        unlock_level = 15,
        rarity = "common",
        stats = {
            damage = { 6, 18 },
            movement = { 10, 24 },
        },
    },
    ["ember_cat"] = {
        name_es = "Gato de Brasa",
        role = "dps_magico",
        unit = "npc_sirv_pet_ember_cat",
        active = "periodic_magic_damage",
        unlock_level = 25,
        rarity = "rare",
        stats = {
            magic_damage = { 5, 14 },
            dodge = { 3, 7 },
        },
    },
    ["mini_roshan"] = {
        name_es = "Roshan Miniatura",
        role = "tanque_dps",
        unit = "npc_sirv_pet_mini_roshan",
        active = "taunt_guard",
        unlock_level = 45,
        rarity = "legendary",
        stats = {
            health = { 180, 420 },
            armor = { 5, 12 },
            damage = { 10, 28 },
        },
    },
    ["grove_sprite"] = {
        name_es = "Espiritu del Claro",
        role = "soporte_healer",
        unit = "npc_sirv_pet_grove_sprite",
        active = "periodic_heal",
        unlock_level = 20,
        rarity = "common",
        stats = {
            heal_amp = { 3, 8 },
            mana = { 50, 120 },
        },
    },
    ["runic_turtle"] = {
        name_es = "Tortuga Runica",
        role = "soporte_defensivo",
        unit = "npc_sirv_pet_runic_turtle",
        active = "taunt_guard",
        unlock_level = 30,
        rarity = "epic",
        stats = {
            health = { 140, 360 },
            armor = { 4, 10 },
        },
    },
    ["clockwork_beetle"] = {
        name_es = "Escarabajo Mecanico",
        role = "soporte_utilidad",
        unit = "npc_sirv_pet_clockwork_beetle",
        active = "periodic_physical_damage",
        unlock_level = 35,
        rarity = "epic",
        stats = {
            damage = { 7, 18 },
            movement = { 8, 20 },
        },
    },
}
