WorldLevelConfig = {
    [1] = {
        ["enemy_health"] = 1.0,
        ["enemy_damage"] = 1.0,
        ["xp"] = 1.0,
        ["gold"] = 1.0,
        ["drop"] = 1.0,
        ["unlock"] = "Disponible desde el inicio.",
    },
    [2] = {
        ["enemy_health"] = 1.35,
        ["enemy_damage"] = 1.18,
        ["xp"] = 1.25,
        ["gold"] = 1.15,
        ["drop"] = 1.06,
        ["unlock"] = "Completar Zona 1.",
    },
    [3] = {
        ["enemy_health"] = 1.8,
        ["enemy_damage"] = 1.38,
        ["xp"] = 1.55,
        ["gold"] = 1.3,
        ["drop"] = 1.12,
        ["unlock"] = "Completar Zona 2.",
    },
    [4] = {
        ["enemy_health"] = 2.4,
        ["enemy_damage"] = 1.65,
        ["xp"] = 1.9,
        ["gold"] = 1.5,
        ["drop"] = 1.18,
        ["unlock"] = "Completar Zona 3.",
    },
    [5] = {
        ["enemy_health"] = 3.2,
        ["enemy_damage"] = 2.0,
        ["xp"] = 2.3,
        ["gold"] = 1.75,
        ["drop"] = 1.25,
        ["unlock"] = "Completar Zona 4.",
    },
    [6] = {
        ["enemy_health"] = 4.0,
        ["enemy_damage"] = 2.35,
        ["xp"] = 2.75,
        ["gold"] = 2.0,
        ["drop"] = 1.32,
        ["unlock"] = "Futuro.",
    },
    [7] = {
        ["enemy_health"] = 5.0,
        ["enemy_damage"] = 2.8,
        ["xp"] = 3.25,
        ["gold"] = 2.3,
        ["drop"] = 1.4,
        ["unlock"] = "Futuro.",
    },
    [8] = {
        ["enemy_health"] = 6.25,
        ["enemy_damage"] = 3.25,
        ["xp"] = 3.8,
        ["gold"] = 2.65,
        ["drop"] = 1.5,
        ["unlock"] = "Futuro.",
    },
    [9] = {
        ["enemy_health"] = 7.8,
        ["enemy_damage"] = 3.8,
        ["xp"] = 4.4,
        ["gold"] = 3.05,
        ["drop"] = 1.62,
        ["unlock"] = "Futuro.",
    },
    [10] = {
        ["enemy_health"] = 9.5,
        ["enemy_damage"] = 4.45,
        ["xp"] = 5.0,
        ["gold"] = 3.5,
        ["drop"] = 1.8,
        ["unlock"] = "Futuro.",
    },
}
